---
title: "filter_join"
author: "Ricky Fong"
date: "24/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(kableExtra)

```

```{r}
fish <- read_csv(here("data", "fish.csv"))
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")

fish_garibaldi <- filter(fish, common_name == "garibaldi")
fish_mohk <- filter(fish, site == "mohk")
fish_over50 <- filter(fish, total_count >= 50)
fish_3sp <- filter(fish, common_name == "garibaldi" | common_name == "blacksmith" | common_name == "black surfperch")
fish_3sp_ii <- filter(fish, common_name %in% c("garibaldi", "blacksmith", "black surfperch"))
fish_gar_2016 <- filter(fish, year == 2016 | common_name == "garibaldi")

aque_2018 <- filter(fish, year == 2018, site == "aque")
aque_2018 <- filter(fish, year == 2018 & site == "aque")

low_gb_wr <- filter(fish, common_name %in% c("garibaldi", "rock wrasse"), total_count <= 10)
```

```{r str_detect}

fish_bl <- filter(fish, str_detect(common_name, pattern = "black"))
fish_bl2 <- filter(fish, str_detect(common_name, pattern = "black", negate = TRUE))

fish_it <- filter(fish, str_detect(common_name, pattern = "it"))
```

```{r join}
abur_kelp_fish <- kelp_abur %>% 
  full_join(fish, by = c("year", "site"))
kelp_abur
fish
abur_kelp_fish

kelp_fish_left <- kelp_abur %>%
  left_join(fish, by = c("year", "site"))
kelp_fish_left

kelp_fish_injoin <- kelp_abur %>%
  inner_join(fish, by = c("year", "site"))
kelp_fish_injoin

kelp_fish_injoin2 <- kelp_abur %>%
  inner_join(fish, by = c("site"))
kelp_fish_injoin2

```

```{r }
fish_2017_abur <- filter(fish, year == 2017, site == "abur")
fish_join <- kelp_abur %>%
  left_join(fish_2017_abur, by = c("site", "year"))
fish_join_final <- mutate(fish_join, fish_per_frond = total_count/total_fronds)

kelp_abur
fish_2017_abur
fish_join
fish_join_final

kable(fish_join_final)

fish_join_final %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)
```

