---
title: "pivot_lobster"
author: "Ricky Fong"
date: "21/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(skimr)
library(kableExtra)
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip = 4)
```

```{r}
skimr::skim(lobsters)
skim(lobsters)
lobsters %>% 
  group_by(year) %>% 
  summarize(count_by_year = n())
lobsters %>%
  summarize(count_total = n())

lobsters %>%
  group_by(year)

lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n())

lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm))

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarise(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm=TRUE),
            sd_size_mm = sd(size_mm, na.rm=TRUE))

siteyear_summary

siteyear_summary %>%
  kable()

siteyear_median_summary <- lobsters %>%
  group_by(site, year) %>%
  summarise(median_size_mm = median(size_mm, na.rm=TRUE))
ggplot(data = siteyear_median_summary, aes(x = year, y = median_size_mm, color = site)) + geom_line()
ggsave(here("figures", "lobsters-line.png"))
ggplot(data = siteyear_median_summary, aes(x = year, y = median_size_mm)) + geom_col() + facet_wrap(~site)
ggsave(here("figures", "lobsters-col.png"))
```

"There are #r nrow(lobsters)# total lobsters included in this report"

