---
title: "plots-ggplot"
author: "Ricky Fong"
date: "20/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)

```

```{r First part}

ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))
gg_base + geom_col()
gg_base + geom_area()
gg_base + geom_line(color = "blue", linetype = "dashed")
gg_base + geom_col(aes(fill = visitors))

gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5) + theme_minimal()
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5)
```

```{r}
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5) + theme_minimal()
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5)
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5) + theme_linedraw()
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5) + theme_classic()
gg_base + geom_line(linetype = "dotted") + theme_bw() + labs(x = "Years", y = "Annual park visitors", title = "Channel Islands NP Visitation", subtitle = "(1963 - 2016)")
gg_base + geom_line(color = "purple") + geom_point(color = "orange", alpha = 0.5)
gg_base + geom_col(fill = "orange") + geom_line(color = "green")
```
```{r}
gg_base + geom_line()
ggplot(data = ca_np, aes(x = year, y = visitors)) + geom_line()
ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_line()
ca_np
ci_np
ggplot(data = ca_np, aes(x = year, y = visitors, group = code)) + geom_line()
ggplot(data = ca_np, aes(x = year, y = visitors, group = code)) + geom_line(aes(color = code))
gg_np + geom_line(show.legend = FALSE) + theme_light() + labs(x = "years", y ="annual visitors") + facet_wrap(~ code)
gg_np + geom_line() + theme_light() + labs(x = "years", y ="annual visitors") + facet_wrap(~ code)
ggsave(here("figures", "np_graph.jpg"))
ggsave(here("figures", "np_graph2.jpg"), dpi = 180, width = 8, height = 7)
ggsave(here("figures", "np_graph2.pdf"), dpi = 180, width = 8, height = 7)
```

