---
title: "Ricky_fisheries"
author: "Ricky Fong"
date: "24/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(paletteer)
```

```{r}
us_landings <- read_csv(here("data", "noaa_landings.csv"), na = "no data")
us_landings
salmon_clean <- clean_names(us_landings)
salmon_clean
salmon_clean2 <- us_landings %>%
  clean_names() %>%
  mutate(
    afs_name = str_to_lower(afs_name)
  ) %>%
  mutate(dollars_num = parse_number(dollars_usd)) %>%
  filter(str_detect(afs_name, pattern = "salmon")) %>%
  separate(afs_name, into = c("group", "subgroup"), sep = ",") %>%
  drop_na(dollars_num)
salmon_clean2

salmon_us_annual <- salmon_clean2 %>%
  group_by(year, subgroup) %>%
  summarise(
    tot_value = sum(dollars_num, na.m = TRUE),
  )
salmon_us_annual
```

```{r}
salmon_gg <- ggplot(salmon_us_annual, aes(x = year, y = tot_value, group = subgroup)) + geom_line(aes(color = subgroup)) + theme_bw() + labs(x = "year", y = "US commercial salmon value (USD)") + scale_color_paletteer_d("palettesForR::Tango")
salmon_gg
```

